site_name: STEMinds Docs
site_url: https://docs.steminds.com/
nav:
  - Welcome: index.md
  - 'Products':
    - 'Extension board for Eduponics Mini' : 'products/eduponics_mini_extension_board.md'
  - 'Kits':
    - 'Eduponics Mini':
      - 'Introduction' : 'kits/eduponics_mini/introduction.md'
      - 'Getting started' : 'kits/eduponics_mini/eduponics_mini_getting_started.md'
      - 'Advance manual tools' : 'kits/eduponics_mini/advance_tools.md'
      - 'BME280 sensor' : 'kits/eduponics_mini/basic_sensors_usage/bme280_temperature_and_humidity.md'
      - 'DHT11 sensor' : 'kits/eduponics_mini/basic_sensors_usage/dht11_temperature_and_humidity.md'
      - 'BH1750 Light sensor' : 'kits/eduponics_mini/basic_sensors_usage/light_sensor.md'
      - 'Water level sensor' : 'kits/eduponics_mini/basic_sensors_usage/water_quantity_sensor.md'
      - 'Water pump' : 'kits/eduponics_mini/basic_sensors_usage/pump.md'
      - 'RGB LED' : 'kits/eduponics_mini/basic_sensors_usage/rgb_led.md'
      - 'EEPROM Module' : 'kits/eduponics_mini/basic_sensors_usage/eeprom_module.md'
      - 'RTC Module' : 'kits/eduponics_mini/basic_sensors_usage/rtc_module.md'
      - 'Soil moisture sensor' : 'kits/eduponics_mini/basic_sensors_usage/soil_moisture_sensor.md'
      - 'Deep sleep wakeup' : 'kits/eduponics_mini/basic_sensors_usage/deep_sleep_wakeup.md'
      - 'RGB based indicators' : 'kits/eduponics_mini/advance_usage/RGB_indicators.md'
      - 'Water level based pump' : 'kits/eduponics_mini/advance_usage/water_level_based_water_pumping.md'
      - 'Introduction to MQTT' : 'kits/eduponics_mini/advance_usage/introduction_to_mqtt.md'
      - 'Basic MQTT client' : 'kits/eduponics_mini/advance_usage/basic_mqtt_client.md'
      - 'Eduponics MQTT APP' : 'kits/eduponics_mini/advance_usage/eduponics_mqtt_app.md'
theme:
  name: material
  logo: https://cdn.steminds.com/docs/images/icon.svg
  favicon: https://cdn.steminds.com/docs/images/icon.svg
  name: material
  language: en
  icon:
    logo: https://cdn.steminds.com/docs/images/icon.svg
  palette:
    primary: default
    accent: amber
plugins:
  - tags
  - privacy
  - social
markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight:
      use_pygments: true
      linenums: false
      linenums_style: pymdownx.inline
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/STEMinds
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/STEMinds
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/STEMinds
  analytics:
    provider: google
    property: G-PW3PQDPSNS
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.